# Note: je fais du port mapping sur tout les services, pour tester si les
# services sont healthy avec /health que founit spring actuator (ops).

services:
  # Database
  postgres:
    image: postgres:18-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wilaya_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - private-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d wilaya_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Later-on when necessary. I'll add volumes

  # Configuration Server
  config-server:
    build:
      context: ./services/config-server
      dockerfile: Dockerfile
    container_name: wilaya_config_server
    ports:
      - "9001:9001"
    networks:
      - private-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Discovery Server
  discovery-server:
    build:
      context: ./services/discovery-server
      dockerfile: Dockerfile
    container_name: wilaya_discovery_server
    ports:
      - "8761:8761"
    networks:
      - private-network
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5


# Networks
networks:
  private-network:
    driver: bridge

# Volumes
